/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package roomreservation.views;

/**
 *
 * @author Cordero
 */
public class EditProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btninicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnreserva = new javax.swing.JButton();
        btnmreservas = new javax.swing.JButton();
        btnadreservas = new javax.swing.JButton();
        btngestusuarios = new javax.swing.JButton();
        btnmcuenta = new javax.swing.JButton();
        lblcorreo = new javax.swing.JLabel();
        lblcont = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btncanc = new javax.swing.JButton();
        txtcorreo = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        psfcontra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        btninicio.setBackground(new java.awt.Color(0, 153, 51));
        btninicio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btninicio.setForeground(new java.awt.Color(255, 255, 255));
        btninicio.setText("Inicio");
        btninicio.setBorder(null);
        btninicio.setContentAreaFilled(false);

        jLabel2.setFont(new java.awt.Font("Vensim Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROOMC");

        btnreserva.setBackground(new java.awt.Color(0, 153, 51));
        btnreserva.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnreserva.setForeground(new java.awt.Color(255, 255, 255));
        btnreserva.setText("Reservar");
        btnreserva.setBorder(null);
        btnreserva.setContentAreaFilled(false);

        btnmreservas.setBackground(new java.awt.Color(0, 153, 51));
        btnmreservas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnmreservas.setForeground(new java.awt.Color(255, 255, 255));
        btnmreservas.setText("Mis reservas");
        btnmreservas.setBorder(null);
        btnmreservas.setContentAreaFilled(false);

        btnadreservas.setBackground(new java.awt.Color(0, 153, 51));
        btnadreservas.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnadreservas.setForeground(new java.awt.Color(255, 255, 255));
        btnadreservas.setText("Administrar reservas");
        btnadreservas.setBorder(null);
        btnadreservas.setContentAreaFilled(false);

        btngestusuarios.setBackground(new java.awt.Color(0, 153, 51));
        btngestusuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btngestusuarios.setForeground(new java.awt.Color(255, 255, 255));
        btngestusuarios.setText("Gestionar usuarios");
        btngestusuarios.setBorder(null);
        btngestusuarios.setContentAreaFilled(false);

        btnmcuenta.setBackground(new java.awt.Color(0, 153, 51));
        btnmcuenta.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnmcuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnmcuenta.setText("Mi cuenta");
        btnmcuenta.setBorder(null);
        btnmcuenta.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmreservas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadreservas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngestusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmreservas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadreservas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngestusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        lblcorreo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblcorreo.setText("Correo");
        jPanel1.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        lblcont.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblcont.setText("Contraseña");
        jPanel1.add(lblcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        lbltel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lbltel.setText("Telefono");
        jPanel1.add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        btnguardar.setText("Guardar");
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        btncanc.setText("Cancelar");
        jPanel1.add(btncanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, -1));
        jPanel1.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 120, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 210, 200));

        psfcontra.setText("jPasswordField1");
        jPanel1.add(psfcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Mi Cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadreservas;
    private javax.swing.JButton btncanc;
    private javax.swing.JButton btngestusuarios;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btninicio;
    private javax.swing.JButton btnmcuenta;
    private javax.swing.JButton btnmreservas;
    private javax.swing.JButton btnreserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcont;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbltel;
    private javax.swing.JPasswordField psfcontra;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
